documents/urls.py
from django.urls import path, include
from documents.views import upload_document, document_list, download_document, delete_document, category_detail, subcategory_detail, get_subcategories
from documents.category_views import CategoryDetail
from documents import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'documents'

urlpatterns = [
    path('upload/', upload_document, name='upload_document'),
    path('', document_list, name='document_list'),
    path('subcategory/<int:subcategory_id>/', views.subcategory_detail, name='subcategory_detail'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('<int:document_id>/download/', download_document, name='download_document'),
    path('<int:document_id>/delete/', delete_document, name='delete_document'),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fijibati/urls.py
from django.contrib import admin
from django.urls import path, include
from documents.models import Document, DocumentCategory


# Admin Site Config
admin.site.site_header = 'Fiji National Rugby League'
admin.site.site_title = 'FNRL Web Admin'
admin.site.index_title = 'FNRL Web Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('documents/', include('documents.urls', namespace='documents')),
    path('registration/', include('registration.urls', namespace='registration')),
]

news/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from allauth import urls as allauth_urls
import allauth





urlpatterns=[
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
    path('mission/',views.mission_view,name='mission'),
    path('govern',views.govern_view,name='govern'),
    path('contact',views.contact_view,name='contact'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/login',views.login_user,name='accounts_login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User, Group
from django.utils import timezone
from django.views.generic import DetailView

class DocumentCategory(models.Model):
    name = models.CharField(max_length=200)
    groups = models.ManyToManyField(Group)
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='subcategories')

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=200)
    groups = models.ManyToManyField(Group)
    category = models.ForeignKey(DocumentCategory, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

class Document(models.Model):
    title = models.CharField(max_length=600)
    file = models.FileField(upload_to='documents/')
    description = models.TextField(blank=True)
    category = models.ForeignKey(DocumentCategory, on_delete=models.CASCADE, null=True)
    subcategory = models.ManyToManyField(SubCategory)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='documents_created')
    groups = models.ManyToManyField(Group, blank=True)

    def __str__(self):
        return self.title

class CategoryDetail(DetailView):
    model = DocumentCategory
    template_name = 'category_detail.html'
    context_object_name = 'category'

documents/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.forms import Textarea
from .models import Document, SubCategory, DocumentCategory

class DocumentForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
    )

    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    category = forms.ModelChoiceField(
        queryset=DocumentCategory.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    subcategory = forms.ModelMultipleChoiceField(
        queryset=SubCategory.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Document
        fields = ['title', 'file', 'description', 'category', 'subcategory', 'groups']
        widgets = {
            'subcategory': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

documents/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Document, DocumentCategory, SubCategory
from .forms import DocumentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import os
from django.core.files.storage import default_storage

@login_required
def upload_document(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            document.author = request.user  # Set the author to the currently logged-in user
            document.save()
            form.save_m2m()
            return redirect('documents:document_list')
    else:
        form = DocumentForm()

    return render(request, 'documents/upload_document.html', {'form': form})

@login_required
def document_list(request):
    categories = DocumentCategory.objects.all()
    return render(request, 'documents/document_list.html', {'categories': categories})

@login_required
def download_document(request, document_id):
    document = get_object_or_404(Document, id=document_id)
    # Perform any permission checks here, if necessary
    return document.file.serve(request, document.file.name)

@login_required
def delete_document(request, document_id):
    document = get_object_or_404(Document, id=document_id)
    # Perform any permission checks here, if necessary
    document.file.delete()
    document.delete()
    return redirect('documents:document_list')

@login_required
def category_detail(request, category_id):
    category = get_object_or_404(DocumentCategory, id=category_id, groups__in=request.user.groups.all())
    categories = DocumentCategory.objects.all()
    return render(request, 'documents/category_detail.html', {'category': category, 'categories': categories})

@login_required
def subcategory_detail(request, subcategory_id):
    try:
        subcategory = SubCategory.objects.get(id=subcategory_id)
        documents = Document.objects.filter(subcategory=subcategory)
        return render(request, 'documents/subcategory_detail.html', {'subcategory': subcategory, 'documents': documents})
    except SubCategory.DoesNotExist:
        return render(request, 'documents/subcategory_not_found.html')

def get_subcategories(request):
    category_id = request.GET.get('category_id')
    subcategories = SubCategory.objects.filter(category_id=category_id).values('id', 'name')
    return JsonResponse({'subcategories': list(subcategories)})

templates/documents/category_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-3 ml-3 mr-3">
    <div class="col-md- mobile-hide">
        <div class="card shadow mr-3 mobile-hide" style="background-color: #000000; font-family: Barlow;">
            <h3 class="ml-2" style="color: #F57E1F;">{{ category.name }}</h3>
        </div>
    </div>
    <div class="col-md-8 mt-3">
        <div class="card mb-3 shadow pl-4 py-4 pr-4 mt-3" style="font-family: Barlow;">
            {% if category %}
                <h4>Subcategories:</h4>
                {% for subcategory in category.subcategory_set.all %}
                    <a href="{% url 'documents:subcategory_detail' subcategory.id %}" class="btn btn-secondary">{{ subcategory.name }}</a>
                {% empty %}
                    <p>No subcategories available for this category.</p>                                                                                                                                                            
                {% endfor %}
                {% else %}
                    <p>You are not authorized to view this category.</p>
            {% endif %}
        </div>
    </div>
    <div class="col-md-4 mt-3">
        <div class="card mb-3 shadow pl-4 py-4 pr-4">
            <button type="button" class="btn btn-dark mt-2"><a href="{% url 'documents:upload_document' %}">Upload Document</a></button>
        </div>
        <div class="card mb-3 shadow pl-4 py-4 pr-4" style="font-family: Barlow;">
            <h5 class="">DOCUMENT CATEGORIES</h5>
            <ul class="list-group mt-3">
                {% for category in categories|dictsort:'name' %}
                <li class="list-group-item">
                    <a href="#">{{ category.name }}</a>
                    {% if category.subcategory_set.all %}
                    <ul class="list-group mt-2">
                        {% for subcategory in category.subcategory_set.all %}
                        <li class="list-group-item">
                            <a href="{% url 'documents:subcategory_detail' subcategory.id %}" class="btn btn-secondary btn-block">{{ subcategory.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>No subcategories available.</p>
                    {% endif %}
                </li>
                {% empty %}
                <li class="list-group-item">No categories available.</li>
                {% endfor %}
            </ul> 
         </div>         
    </div>     
</div>
{% endblock %}

templates/documents/document_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-3 ml-3 mr-3">
  <div class="col-md-12 mobile-hide">
    <div class="card shadow mr-3 mobile-hide" style="background-color: #000000; font-family: Barlow;">
      <h3 class="ml-2" style="color: #F57E1F;">DOCUMENT CATEGORIES/</h>
    </div>
  </div>
  <div class="col-md-12 mt-3">
    <div class="card mb-3 shadow pl-4 py-4 pr-4">
      <div class="row">
        {% for category in categories|dictsort:'name' %}
          <div class="col-md-3">
            <a href="#" class="btn btn-dark btn-block my-2">{{ category.name }}</a>
            {% if category.subcategory_set.all %}
              {% for subcategory in category.subcategory_set.all %}
                <div class="ml-3">
                  <a href="{% url 'documents:subcategory_detail' subcategory.id %}" class="btn btn-secondary btn-block my-2">{{ subcategory.name }}</a>
                </div>
              {% endfor %}
            {% else %}
              <p>No subcategories available.</p>
            {% endif %}
          </div>
        {% empty %}
          <p>No categories available.</p>
        {% endfor %}
      </div>
    </div>      
  </div>
</div>
{% endblock %}

templates/documents/subcategory_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-3 ml-3 mr-3">
    <div class="col-md-12 mobile-hide">
        <div class="card shadow mr-3 mobile-hide" style="background-color: #000000; font-family: Barlow;">
            <h3 class="ml-2" style="color: #F57E1F;">{{ subcategory.name }}</h3>
        </div>
    </div>
</div>
<div class="row my-3 ml-3 mr-3">
    <div class="col-md-8 mt-3">
        <div class="card mb-3 shadow pl-4 py-4 pr-4">
            <div class="row">
                {% for document in documents %}
                    <h4 class="mt-3">{{ document.title }}</h4>
                    <p>Author: {{ document.author.username }}</p>
                    <h6>Description: {{ document.description }}</h6>                
                    <a href="{{ document.file.url }}" target="_blank" class="btn btn-dark btn-block my-2">View File</a>
                    <a class="btn btn-dark  btn-d " href="{{ document.file.url }}" download type="submit"><i style="font-family: Barlow;">Download File</i></a>
                    <!-- Add any other fields or information you want to display -->
                {% empty %}
                    <p>E se lala toka a noke kaiei...</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-4 mt-3">
        <div class="card mb-3 shadow pl-4 py-4 pr-4">
            <button type="button" class="btn btn-dark"><a href="{% url 'documents:document_list' %}">Document Categories</a>
            <button type="button" class="btn btn-dark mt-2"><a href="{% url 'documents:upload_document' %}">Upload Document</a></button>
        </div>
        <div class="card mb-3 shadow pl-4 py-4 pr-4" style="font-family: Barlow;">
            <h5 class="">DOCUMENT CATEGORIES</h5>
            <ul class="list-group mt-3">
                <div class="row">
                    {% for category in categories|dictsort:'name' %}
                        <li class="list-group-item">
                            <a href="{% url 'documents:category_detail' category.id %}" class="btn btn-dark btn-block">{{ category.name }}</a>
                            {% if category.subcategory_set.all %}
                            <ul class="list-group mt-2">
                                {% for subcategory in category.subcategory_set.all %}
                                <li class="list-group-item">
                                    <a href="{% url 'documents:subcategory_detail' subcategory.id %}" class="btn btn-secondary btn-block">{{ subcategory.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                            {% else %}
                            <p>No subcategories available.</p>
                            {% endif %}
                        </li>
                    {% empty %}
                    <li class="list-group-item">No categories available.</li>
                    {% endfor %}
                </div>
            </ul> 
         </div>         
    </div>     
</div>
{% endblock %}

templates/documents/upload_document.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-3 ml-4 mr-4">
    <div class="col-md-12 mobile-hide">
        <div class="card shadow mr-3 mobile-hide" style="background-color: #000000;">
            <h3 class="ml-2" style="color: #F57E1F;">UPLOAD DOCUMENT</h3>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card mb-3 shadow pl-4 py-4 pr-4 mt-3" style="overflow-y: scroll; max-height: 90vh;">
            <h4>Please Fill in this Form to upload a document</h4>
            <form method="post" action="{% url 'documents:upload_document' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark">Upload Document</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}