documents/urls.py
from django.urls import path, include
from documents.views import upload_document, document_list, download_document, delete_document, category_detail, subcategory_detail, get_subcategories
from documents.category_views import CategoryDetail
from documents import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'documents'

urlpatterns = [
    path('upload/', upload_document, name='upload_document'),
    path('', document_list, name='document_list'),
    path('subcategory/<int:subcategory_id>/', views.subcategory_detail, name='subcategory_detail'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('<int:document_id>/download/', download_document, name='download_document'),
    path('<int:document_id>/delete/', delete_document, name='delete_document'),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fijibati/urls.py
from django.contrib import admin
from django.urls import path, include
from documents.models import Document, DocumentCategory


# Admin Site Config
admin.site.site_header = 'Fiji National Rugby League'
admin.site.site_title = 'FNRL Web Admin'
admin.site.index_title = 'FNRL Web Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('documents/', include('documents.urls', namespace='documents')),
    path('registration/', include('registration.urls', namespace='registration')),
]

news/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from allauth import urls as allauth_urls
import allauth





urlpatterns=[
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
    path('mission/',views.mission_view,name='mission'),
    path('govern',views.govern_view,name='govern'),
    path('contact',views.contact_view,name='contact'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/login',views.login_user,name='accounts_login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from tinymce.models import HTMLField
from django.utils.safestring import mark_safe
from tinymce.widgets import TinyMCE
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User, AbstractUser, Group, Permission
from private_storage.fields import PrivateFileField



# Member Profile
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, blank=True)
    # Add additional fields to your profile model as needed
    bio = models.TextField()

    def __str__(self):
        return self.user.username

class CustomUser(AbstractUser):
    groups = models.ManyToManyField(Group, related_name='users')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_users')


# Category Model
class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='images/')

    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title

# News Model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    author = models.CharField(max_length=255)
    image=models.ImageField(upload_to='images/')
    body=HTMLField()
    pub_date=models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])

    class Meta:
        verbose_name_plural='News'

    def __str__(self):
        return self.title


#Featured Article
class FeaturedArticle(models.Model):
    news = models.ForeignKey(News, on_delete=models.SET_NULL, null=True)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.news.title if self.news else ''

    def save(self, *args, **kwargs):
        # Ensure only one article can be featured at a time
        if self.is_featured:
            FeaturedArticle.objects.exclude(pk=self.pk).update(is_featured=False)
        super().save(*args, **kwargs)




# Comments
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

# Visitor Counter
class Visitor(models.Model):
    ip_address = models.GenericIPAddressField()
    timestamp = models.DateTimeField(auto_now_add=True)

#Document Storage
class DocumentCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Document(models.Model):
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to='documents/')
    description = models.TextField(blank=True)
    category = models.ForeignKey(DocumentCategory, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from .models import Document


class DocumentForm(forms.ModelForm): 
    class Meta:
        model = Document
        fields = ('title', 'file', 'description', 'category')

news/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from .models import News, Category, Comment, FeaturedArticle, Visitor
from django.views import View
from django.http import HttpResponse
from django.utils.timesince import timesince
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import Group
from .forms import DocumentForm
from documents.models import Document, DocumentCategory



   
# Login
def login_user(request):
    return LoginView.as_view(template_name='login.html')(request)


# Profile
def profile(request):
    groups = request.user.groups.all()
    return render(request, 'profile.html', {'groups': groups})

def my_view(request):
    # your view logic
    return render(request, 'my_template.html', {'user': request.user})


# Home
def home(request):

    three_categories = Category.objects.all()[:3]
    first_news= News.objects.first()  # Retrieve the first featured news item
    three_news=News.objects.all()[1:3]
    card_text = first_news.body.split()[:50] if first_news else []
    card_text = ' '.join(card_text)
    featured_articles = FeaturedArticle.objects.filter(is_featured=True)
    #for visitor counter
    visitor_ip = request.META.get('REMOTE_ADDR')
    visitor, created = Visitor.objects.get_or_create(ip_address=visitor_ip)
    visitor_count = Visitor.objects.count()

    news_list = []
    for category in three_categories:
        news_list.extend(category.news_set.all())
    
    sorted_news = sorted(news_list, key=lambda news: news.pub_date, reverse=True)
     
    return render(request, 'home.html', {
        'visitor_count': visitor_count, 
        'first_news': first_news, 
        'three_news': three_news, 
        'three_categories': three_categories, 
        'featured_articles': featured_articles, 
        'sorted_news': sorted_news[:12],
    })


# All News
def all_news(request):
    all_news=News.objects.all()
    three_categories = Category.objects.all()[:3]

    news_list = []
    for category in three_categories:
        news_list.extend(category.news_set.all())
    
    sorted_news = sorted(news_list, key=lambda news: news.pub_date, reverse=True)

    return render(request,'news/all-news.html',{
        'all_news':all_news,
        'sorted_news': sorted_news[:24],
    })

# Detail Page
def detail(request,id):
    news=News.objects.get(pk=id)
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        comment=request.POST['message']
        Comment.objects.create(
            news=news,
            name=name,
            email=email,
            comment=comment
        )
        messages.success(request,'Comment submitted but in moderation mode.')
    category=Category.objects.get(id=news.category.id)
    rel_news=News.objects.filter(category=category).exclude(id=id)
    comments=Comment.objects.filter(news=news,status=True).order_by('-id')
    return render(request,'detail.html',{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })

# Fetch all category
def all_category(request):
    cats=Category.objects.all()
    return render(request,'category.html',{
        'cats':cats
    })


# Fetch all category
def category(request,id):
    category=Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    return render(request,'category-news.html',{
        'all_news':news,
        'category':category
    })

# Mission
def mission_view(request):
    return render(request,'mission.html')

# Governed
#Mission
def govern_view(request):
    return render(request,'govern.html')

# Contact
def contact_view(request):
    return render(request,'contact.html')

# Facebook Share
class OpenGraphView(View):
    def get(self, request, news_id):
        news = get_object_or_404(News, id=news_id)
        meta_tags = f'''
        <meta property="og:url" content="http://fnrladmin.pythonanywhere.com/detail/{news.id}" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="{news.title}" />
        <meta property="og:description" content="{news.description}" />
        <meta property="og:image" content="http://fnrladmin.pythonanywhere/media/{news.image}" />
        '''

        return HttpResponse(meta_tags)

# News Cards 
def news_card(request):
    # Assuming you have a queryset or list of news articles
    news_articles = News.objects.all()  # Replace NewsArticle with your actual model

    # Calculate the time difference in minutes between the current time and publication time
    for article in news_articles:
        article.minutes_ago = int(timesince(article.pub_date).split()[0])

    context = {
        'news_articles': news_articles,
    }
    return render(request, 'news_card.html', context)

# News Cards stack
def news_list(request):
    articles = News.objects.order_by('-pub_date')  # Retrieve articles ordered by the latest publication date
    return render(request, 'news_list.html', {'articles': articles})


    

templates/news/all-news.html
{% extends 'base.html' %}
{% block content %}

<div class="row my-3 ml-3">
	<!-- Header Banner -->
	<div class="col-md-12 mobile-hide">
		<div class="card shadow mr-3 mobile-hide" style="background-color: #000000;">
			<h3 class="ml-2" style="color: #F57E1F;">NEWS/</h>
		</div>
	</div>
	<div class="row my-4">
		{% for news in sorted_news %}
		<div class="col-md-3">
			<!-- News box -->
			<a href="/detail/{{ news.id }}">
			<div class="card shadow" style="background-color: black; color:#F57E1F; height: 300px; display: flex; flex-direction: column; border-radius: 10px; margin-bottom: 20px;">
				<img src="/media/{{ news.image }}" class="card-img-top" style="object-fit: cover; height: 120px;" alt="{{ news.title }}">
				<div class="card-body">
					<h6 class="card-title" style="font-size: 12px;">{{ news.category.title }}</h6>
					<h5 class="ml-2" style="color:#F57E1F; font-size: 14px;">{{ news.title }}</h5>
					<h6 class="card-footer" style="position: absolute; bottom: 0; left: 0; right: 0; font-size: 12px;">{{ news.pub_date|timesince }} ago</h6>
				</div>
			</div>
		</a>
		</div>
		{% endfor %}
	
	</div>
	 
</div>

{% endblock %}

templates/news/category-news.html
{% extends 'base.html' %}
{% load custom_filter %}
{% block content %}
<div class="row my-4 ml-4 mr-4">
	<div class="col-md-12">
			<div class="flex p-1" style="background-color: #5B2A00;"">
				<h3 style="color: #F57E1F;">{{category.title}}</h>
			</div>
			{% for news in all_news %}
			<a href="/detail/{{news.id}}">
			<div class="card mb-4 mt-3 shadow">
			<div class="row no-gutters">
				<div class="col-md-3">
					<img src="/media/{{news.image}}" class="card-img-top mt-3" alt="{{news.title}}">
				</div>
				<div class="col-md-8">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<p class="card-text">{{news.body |truncate_words:50 | safe}}</p>
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</div>
			</div>
			</a>
			{% endfor %}
	</div>
</div>
{% endblock %}

templates/news/category.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-4 ml-4 mr-4">
	<div class="col-md-12">
		<div class="flex p-1" style="background-color: #5B2A00;">
			<h3 style="color: #F57E1F;">{{cat.title}}</h3>
		</div>
	</div>
				<!-- Category Box -->
			{% for cat in cats %}
			<div class="col-md-4 mt-3">
				<a href="category/{{cat.id}}">
				<div class="card mb-3 shadow">
				<img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
				<div class="card-body">
					<h5 class="card-title">{{cat.title}}</h5>
					<hr/>
					<p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">Related</a></p>
				</div>
				</div>
				</a>
			</div>
			{% endfor %}
		
</div>	
{% endblock %}

templates/news/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="row my-4 ml-4 mr-4">
	<!-- Left -->
	<div class="col-md-12 ">
		<div class="card mb-3 pl-3 py-3 pr-3 " style="text-align: center;">
			<h3 class="fw-bold">Head Office Location</h3> 
				<h4>57 Richards Road,Domain, Suva City, Fiji</h4>
				<br>
				<i class="fa fa-phone-volume fa-3x"></i>
                <h4>+679 998 1056</h4>
				<br>
				<h3 class="fw-bold">Follow Us</h3> 
				<a href="https://www.facebook.com/fijirugbyleague" target="_blank" rel="noopener noreferrer">
					<i class="fab fa-facebook fa-3x"></i>
				  </a>
				<br>
				<a href="https://twitter.com/fijirugbyleague" target="_blank" rel="noopener noreferrer">
					<i class="fab fa-twitter fa-3x"></i>
				  </a>
				<br>
				<a href="https://www.instagram.com/fijirugbyleague/" target="_blank" rel="noopener noreferrer">
					<i class="fab fa-instagram fa-3x"></i>
				  </a>
<span class="sr-only"></span>
				
			
		</div>
	</div>
</div>
			

{% endblock %}

templates/news/detail.html
{% extends "base.html" %}

{% block content %}

<div class="row my-2 ml-2 mr-2 bg-light">
    <div class="col-md-12">
        <div class="flex p-1 my-2" style="background-color: #000;">
            <h3 class="ml-2" style="color: #F57E1F; text-align:center; font-family: Barlow;">{{ news.title }}</h3>
        </div>
    </div>
    <div class="col-md-8 mt-3">
        <div class="card mb-3 mt-5 shadow" style="background-color: black">
            <img src="/media/{{ news.image }}" class="card-img-top" alt="{{ news.title }}">
            <div class="card-body" style="color: #ffffff; font-size: larger;">
                <h5 class="card-title" style="color: #F57E1F; font-weight: 200; font-family: Barlow;">{{ news.title }}</h5>
                <hr/>
                <p class="card-text" style="color: #ffffff;">{{ news.body | linebreaks | safe }}</p>
            </div>
            <div class="card-footer" style="color: #F57E1F;">
                Related <a href="/category/{{ news.category.id }}">{{ news.category.title }}</a>
                <div class="fb-share-button" data-href="/detail/{{ news.id }}" data-layout="button_count"></div>
            </div>
        </div>
    </div>
    <!-- Related News -->
    <div class="col-md-4">
        <h3 class="mb-3 border-bottom pb-1" style="color: #F57E1F; font-family: Barlow;">Related News</h3>
        <!-- Category Box -->
        {% for news in related_news %}
            <a href="/detail/{{ news.id }}"></a>
            <div class="card mb-3 shadow" style="background-color: black;">
                <img src="/media/{{ news.image }}" class="card-img-top" alt="{{ news.title }}">
                <div class="card-body">
                    <h5 class="card-title" style="color: #F57E1F; font-family: Barlow;">{{ news.title }}</h5>
                    <hr/>
                    <p class="card-text"><a href="/detail/{{ news.id }}" class="btn btn-sm btn-primary">Read Full</a></p>
                </div>
            </div>
            </a>
        {% endfor %} 
    </div>
</div>
<script>
    window.fbAsyncInit = function() {
  FB.init({
    appId: '1231385624248397',
    xfbml: true,
    version: 'v12.0'
  });

  // Set the data-href attribute dynamically
  var newsId = "{{ news.id }}";  // Replace with your actual template syntax or variable
  var shareButton = document.querySelector('.fb-share-button');
  if (shareButton) {
    shareButton.setAttribute('data-href', '/detail/' + newsId);
    FB.XFBML.parse(shareButton);
  }

  // Share button click event
  shareButton.addEventListener('click', function() {
    FB.ui({
      method: 'share',
      href: '/detail/' + newsId,
      quote: "{{ news.title }}"
    });
  });
};


  </script>
  

{% endblock %}

templates/news/eg.html
{% extends "base.html" %}

{% block content %}
<head>
	<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v16.0" nonce="qAHasQ26"></script>
  </head>
  
  
<div class="row my-4 ml-4 mr-4 bg-dark">
	<div class="col-md-12">
		<div class="flex p-1" style="background-color: #5B2A00;">
			<h3 style="color: #F57E1F;">{{ news.title}}</h3>
		</div>
	</div>
		<div class="col-md-8 mt-3">
			<div class="card mb-3 mt-5 shadow" style="background-color: black">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body" style="color: #F57E1F; font-size: larger;">
			    <h5 class="card-title" style="color: #F57E1F; font-weight: 200;">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text" style="color: #F57E1F;">{{news.body | safe}}</p>
			  </div>
			  <div class="card-footer">
			  	Related <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
				 
			  </div>
			</div>			  
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1" style="color: #F57E1F;">Related News</h3>
			<!-- Category Box -->
				{% for news in related_news %}
				<a href="/detail/{{news.id}}"></a>
				<div class="card mb-3 shadow" style="background-color: black;">
					<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title" style="color: #F57E1F;">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</a>
				{% endfor %}	
			
		</div>
		<div class="fb-share-button" data-href="/detail/{{news.id}}" data-layout="button" data-size="large">
			Share on Facebook
		  </div>
		
	</div>


{% endblock %}

templates/news/govern.html
{% extends 'base.html' %}
{% block content %}
<div class="row my-3 ml-4 mr-4">
      <div class="col-md-12">
            <div class="card mb-3 shadow pl-4 py-4 pr-4">
                  <h3 class="fw-bold">Governance</h3> 
                        <h4>The Fiji National Rugby League Ltd is the single controlling body and administrator of the Game.
                  The Fijian government recognition of the sport in 1992 gave way for the formal administration of the sport by an executive committee under the Fiji National Rugby League.
                  The formation of the Fiji National Rugby League Ltd in September of 1998 was an historic opportunity to streamline Rugby League's governance structures and to provide a single point for all strategic direction.
                  <br>
                  <br>In steering the strategic direction of the game, the league ensures that game maintains the highhest level of professionalism. The enthusiasm of the twenty-two FNRL Vodafone Premiership teams, the history and heritage of the Fiji Bati, the unrivalled excitement of Vanua State of Origin, the grassroots enthusiasm of many regular competition participants and the unbridled fun and opportunity that comes to those in the community each year who find Rugby League through school visits, player appearances, matches and respect and social inclusion programs are coordinated through the one independent body.
                  <br>
                  <br>Chaired by Rear Admiral Viliame Naupoto, the Board of Directors brings together a uniquely qualified array of business and sporting leaders who act as trustees of the game. Together they work with the league's administrative executive, to foster, develop, and grow the game and provide adequate funding for Rugby League at all levels.
                  <br>
                  <br>The Board of Directors is governed by the company's article and a board charter congruent to the governance manual. The charter assists the corporation’s leadership in delivering good governance; documents the policies that the board has decided upon to meet its legal and other responsibilities; serves as a reminder for the board of the legal framework within which it operates; is a point of reference for disputes; serves as an induction tool for new directors and senior managers; greatly assists in establishing effective operating procedures for a board; and develops of a shared understanding of the board’s role throughout the organisation.
                  <br>
                  <br>Rugby League's honorary role of Patron is  a celebrated office of the league and traditionally accorded to the Head of State of Fiji. It is a source of guardianship and advocacy in what the Game stands for.
                  As part of the wider International Rugby League community, the Fiji National Rugby League represents a new era for Rugby League for the millions who live and breathe the exhilaration of the Greatest Game of All.</h4>
                        
                  <h3 class="fw-bold">How the League Works</h3>
                  <h4>The Objects of the FNRL Ltd are listed in its articles:
            The primary objects of the League are to:
            <br>
            <br>1. Be the single controlling body and administrator of the Game;
            <br>
            <br>2. Foster, develop, extend and provide adequate funding for the Game from the junior to elite levels and generally to act in the best interests of the Game;
            <br>
            <br>3. Liaise with and delegate appropriate functions to governing bodies of the Game in the States and Zone/Regions of Fiji, including the East and West;
            <br>
            <br>4. Organise and conduct all Vanua State of Origin and Fijian Representative Games;
            <br>
            <br>5. Organise, conduct and foster the FNRL Premiership & Club Competitions;
            <br>
            <br>6. Organise, conduct and foster the Schools Competitions;
            <br>
            <br>7. Liaise with the International Rugby League Limited and organisations controlling the game in other countries in the fostering and control of the game of Rugby League throughout the world;
            <br>
            <br>8. Promote and encourage either directly or indirectly the physical, cultural and intellectual welfare of young people in the community and, in particular, the Rugby League community;
            <br>
            <br>9. Promote and encourage either directly or indirectly sport and recreation, particularly Rugby League football, in the interests of the social welfare of young persons. 
            <br>
            <br>All FNRL clubs and the East, West and Regional Rugby Leagues are members of the League.
            Each club signs a participation agreement which allows it to compete in the Vodafone Premiership.
            <br>
            <br>The Board of Directors are appointed by the league and 2 Directors are appointed by affiliates.
            The Directors are elected by Members and rotated on differing terms. Each Director must, at a nominated time, resign and may seek re-election.</h4>
            </div>
      </div>
      <div class="col-md-4">
            {% for category in three_categories %}
            <h3 class="border-bottom pb-1 ml-4">{{category.title}} <a href="/category/{{category.id}}" class=" btn btn-sm btn-dark ml-4">More</a></h3>
            <div class="row my-4 ml-3 mr-3">
                  {% for news in category.news_set.all %}
                        {% if forloop.counter < 5 %}
                        <!-- News box -->
                        <div class="col-md-3">
                              <div class="card mb-3 shadow" style="height: 300px;">
                                    <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
                                    <div class="card-body">
                                          <h5 class="card-title">{{news.title}}</h5>
                                          <hr/>
                                          <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
                                    </div>
                              </div>
                        </div>
                        {% endif %}
                  {% endfor %}
            </div>
            {% endfor %}

      </div>
</div>
{% endblock %}

templates/news/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light float-right">

      <button type="button" id="sidebarCollapse" class="btn btn-primary">
        <i class="fa fa-bars"></i>
        <span class="sr-only">Toggle Menu</span>
      </button>
      <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fa fa-bars"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item active">
              <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Portfolio</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/news/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div style="background-color: #000;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-xl-11">
                    <div class="card" style="border-radius: 1rem;">
                        <div class="row g-0">
                                <div class="col-md-6 col-lg-5 d-none d-md-block" style="background-image: url('media/images/loginlogo.png'); background-repeat: no-repeat; background-position: center;">
                                </div>                          
                                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                                <div class="card-body p-4 p-lg-5 text-black">

                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <i class="fa-solid fa-anchor-lock fa-3x me-3" style="color: #ff6219;"></i>
                                        <span class="h1 fw-bold mb-0">FNRL Login</span>
                                    </div>

                                    <form method="post" action="{% url 'profile' %}" class="crispy-forms-disabled">
                                        {% csrf_token %}

                                        <div class="form-outline mb-4">
                                            {{ form.username|as_crispy_field }}
                                        </div>

                                        <div class="form-outline mb-4">
                                            {{ form.password|as_crispy_field }}
                                        </div>

                                        <button class="btn btn-dark btn-lg btn-block" type="submit">Login</button>

                                        <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'account_signup' %}" style="color: #393f81;">Register here</a></p>

                                        <p class="small text-muted">Forgot your password? <a href="{% url 'account_reset_password' %}" style="color: #393f81;">Reset it here</a></p>

                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

templates/news/profile11.html
{% extends 'base.html' %}
{% block content %}
<div class="row my-3 ml-3 mr-3">
    <div class="col-md-12 my-3">
      <div class="card mb-3 shadow hover-effect pl-3 py-3 pr-3">
        <h3 class="fw-bold">My Profile Dashboard </h3> 
              <h4>Bula vinaka, {{ user.username }}</h4>
      </div>
    </div>
</div>
<div class="row my-3 ml-3 mr-3">
    <div class="col-md-6">
      <div class="card mb-3 shadow hover-effect pl-3 py-3 pr-3">
        <h4> {{ user.first_name }} , your FNRL Web Administration.</h4> 
        {% if request.user.is_staff %}
        <button type="button" class="btn btn-dark"><a href="{% url 'admin:index' %}">Your FNRL Web Admin Dashboard</a></p>          
        <button type="button" class="btn btn-dark mt-2"><a href="{% url 'account_logout' %}">Logout</a></button>
        {% endif %}
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-3 shadow hover-effect pl-3 py-3 pr-3">
        <h4> {{ user.first_name }} , your FNRL Documents</h4> 
        <button type="button" class="btn btn-dark"><a href="{% url 'documents:document_list' %}">DocuDDDment Categories</a>
        <button type="button" class="btn btn-dark mt-2"><a href="{% url 'documents:upload_document' %}">Upload Document</a>           
      </div>
    </div>
</div>
{% endblock %}